export const CHANGE_CURRENT_SONG = 'CHANGE_CURRENT_SONG';
export const CHANGE_PLAY_STATE = 'CHANGE_PLAY_STATE';
export const CHANGE_LOOP_TYPE = 'CHANGE_LOOP_TYPE';
export const CHANGE_PLAY_LIST = 'CHANGE_PLAY_LIST';
export const SHOW_PLAYER = 'SHOW_PLAYER';
export const CHANGE_PLAYER_SIZE = 'CHANGE_PLAYER_SIZE';
export const NEXT_SONG = 'NEXT_SONG';
export const PREV_SONG = 'PREV_SONG';
